spring:
  profiles:
    active: dev
  application:
    name: ms-platform-config
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.2.250:1433;DatabaseName=PlatformSupportDB;integratedSecurity=false
    username: msdbuser
    password: msdbuser!17
    maxActive: 20
    initialSize: 2
    maxWait: 60000
    minIdle: 2
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    type: com.alibaba.druid.pool.DruidDataSource
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,logback
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jpa:
    #database-platform: org.hibernate.dialect.SQLServer2012Dialect
    database-platform: com.ms.platform.server.config.web.db.SqlServer2012Dialect
    database: sql_server
    open-in-view: true
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      dialect: com.ms.platform.server.config.web.db.SqlServer2012Dialect
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  zipkin:
      base-url: http://192.168.2.111:9411
      enabled: true
  sleuth:
      sampler:
        percentage: 0.8
  data:
    jpa:
      repositories:
        enabled: true

sample:
  zipkin:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.111:8761/eureka/
  instance:
      prefer-ip-address: true

logging:
  file: /data/logs/config-console/server.log
  level:
    root: INFO
    org.springframework.security: DEBUG

security:
  jwt:
    secret: c18e5617bdc02f36429ec81b92e0e27b6fa40d80
    expirationInSeconds: 86400

